name: mugilanportfolio
description: My Own PortFolio , made and Design by Mugilan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  velocity_x: ^4.3.1
  google_fonts: ^6.2.1
  url_launcher: ^6.0.3
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.0.0
  go_router: ^14.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MySocialIcons
      fonts:
        - asset: assets/fonts/MySocialIcons.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
